name: Basic-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  peek-date:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print-date
        run: date +"%d/%m/%Y"
